# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=500)),
                ('attribute_name', models.CharField(max_length=500)),
                ('json_attribute', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('json_attribute', jsonfield.fields.JSONField()),
            ],
        ),
    ]
