# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-19 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panacea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=500)),
                ('json_attribute', jsonfield.fields.JSONField()),
            ],
        ),
    ]
