"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '58ema(eszi_!-)2*9izewm7o3^8a1n-*cv-5#qxm8#%th3fi_t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'panaceauncc.com',
    '127.0.0.1',
    '18.222.65.240',
    '10.108.4.187',
    '*',
]

# User substitution
# https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#auth-custom-user

# AUTH_USER_MODEL = 'emailmutation.User'

# Application definition

INSTALLED_APPS = [
    'panacea.apps.PanaceaConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'activeinvestigation',
    #     'USER': 'mislam7',
    #     'PASSWORD': '',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # },
    # 'panacea': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'activeinvestigation',
    #     'USER': 'mislam7',
    #     'PASSWORD': '',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
    # 'default': {
    #     # 'ENGINE': 'django.db.backends.mysql',
    #     'ENGINE': 'mysql.connector.django',
    #     'NAME': 'activeinvestigation',
    #     'USER': 'root',
    #     'PASSWORD': 'root',
    #     # 'HOST': '3.17.10.16',
    #     'HOST': '13.58.183.216',
    #     'PORT': '3306',
    # },
    # 'panacea': {
    #     # 'ENGINE': 'django.db.backends.mysql',
    #     'ENGINE': 'mysql.connector.django',
    #     'NAME': 'activeinvestigation',
    #         'USER': 'root',
    #         'PASSWORD': 'root',
    #         'HOST': '13.58.183.216',
    #         'PORT': '3306',
    # }
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'activeinvestigation',
        # 'USER': 'root',
        # 'PASSWORD': 'root',
        # 'HOST': '3.17.10.16',
        # 'HOST': '13.58.183.216',
        # 'PORT': '3306',
    },
    'panacea': {
        # 'ENGINE': 'django.db.backends.mysql',
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'activeinvestigation',
        # 'USER': 'root',
        # 'PASSWORD': 'root',
        # 'HOST': '13.58.183.216',
        # 'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/static/',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
EXTERNAL_SCRIPT_ROOT = os.path.join(BASE_DIR, 'exscript')

LOGIN_REDIRECT_URL = '/'
